### ISSUE TITLE
`as const` assertion fails inside class properties while working in module scope

### ISSUE THREAD

**Issue by max-got** [sveltejs/vite-plugin-svelte#1018]
### Describe the bug

I don't know if i am in the correct repo. However, since it concerns svelte and the stacktrace throws vite-plugin-svelte as the cause, I'll open an issue here. Otherwise you can simply move it.

Using `as const` type assertion in a class inside a`<script module lang="ts">` produces `Internal server error: Not implemented TSAsExpression`. It is possible in a `.svelte.ts`file tho.

### Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-bsfhwa?file=src%2Froutes%2F%2Bpage.svelte

### Reproduction

1. Use a `<script module lang="ts">` in a `.svelte`Component
2. Create a class in the module
3. assert `as const` to a property
4. Error: `Not implemented TSAsExpression`

```ts
//comp.svelte
<script module lang="ts">
    const foo = "bar" as const //works
    class Test {
        foo = "bar" as const // breaks : Not implemented TSAsExpression
    }
</script>
```
```ts
//script.svelte.ts
    const foo = "bar" as const // works
    class Test {
        foo = "bar" as const // works
    }
```

### Logs

```shell
Internal server error: Not implemented TSAsExpression
  Plugin: vite-plugin-svelte
  File: /home/projects/stackblitz-starters-bsfhwa/src/routes/+page.svelte
      at handle (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:62:9)
      at PropertyDefinition (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:1084:4)
      at handle (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:70:2)
      at handle_body (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:268:3)
      at BlockStatement|ClassBody (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:463:3)
      at handle (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:70:2)
      at ClassDeclaration|ClassExpression (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:567:3)
      at handle (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:70:2)
      at handle_body (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:268:3)
      at Program (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:1044:3) (x2)
{
  name: 'Error',
  id: '/home/projects/stackblitz-starters-bsfhwa/src/routes/+page.svelte',
  message: 'Not implemented TSAsExpression',
  frame: '',
  code: undefined,
  stack: 'Error: Not implemented TSAsExpression\n' +
    '    at handle (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:62:9)\n' +
    '    at PropertyDefinition (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:1084:4)\n' +
    '    at handle (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:70:2)\n' +
    '    at handle_body (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:268:3)\n' +
    '    at BlockStatement|ClassBody (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:463:3)\n' +
    '    at handle (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:70:2)\n' +
    '    at ClassDeclaration|ClassExpression (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:567:3)\n' +
    '    at handle (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:70:2)\n' +
    '    at handle_body (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:268:3)\n' +
    '    at Program (file:///home/projects/stackblitz-starters-bsfhwa/node_modules/.pnpm/esrap@1.2.2/node_modules/esrap/src/handlers.js:1044:3)',
  plugin: 'vite-plugin-svelte',
  pluginCode: '<script module lang="ts">\n' +
    '  const foo = "bar" as const //works\n' +
    '\tclass Test {\n' +
    '\t\tfoo = "bar" as const // breaks\n' +
    '\t}\n' +
    '</script>\n'
}
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1 
    @sveltejs/kit: ^2.0.0 => 2.7.7 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.0 
    svelte: ^5.0.0 => 5.1.10 
    vite: ^5.0.3 => 5.4.10
```

**Comment by dominikg** [comment]
you have to enable typescripy script preprocessor for this i think.

https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md#enable-script-preprocessing-for-advanced-typescript-syntax-use

**Comment by max-got** [comment]
You're totally right, that indeed works, i didn't know that-  but it's pretty odd that `as const` works in the module scope and in .svelte.ts files, but breaks inside classes without the TypeScript preprocessor enabled. While enabling it fixes the issue, this inconsistent behavior is quite confusing. What do you think?
