### ISSUE TITLE
SCSS preprocessing in Svelte dependencies since Vite 2.7

### ISSUE THREAD

**Issue by hobbes7878** [sveltejs/vite-plugin-svelte#233]
### Describe the bug

Originally posted in SvelteKit -- https://github.com/sveltejs/kit/issues/3071 -- but have reproduced the issue with just this plugin and vite.

Since Vite 2.7, dependencies with SCSS styles -- i.e., `<style lang="scss">` -- are throwing an invalid loader error.

In the reproduction, we get the error even without importing the dependency directly. So I figure probably b/c it's getting included in Vite's dependency pre-bundling, which got all changed in 2.7.

Would be grateful for any help.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-sdyxui?file=vite.config.js

### Logs

```shell
error when starting dev server:
Error: Build failed with 1 error:
error: Invalid loader: "scss" (valid: js, jsx, ts, tsx, css, json, text, base64, dataurl, file, binary)
    at failureErrorWithLog (/home/projects/vitejs-vite-sdyxui/node_modules/esbuild/lib/main.js:1493:15)
    at eval (/home/projects/vitejs-vite-sdyxui/node_modules/esbuild/lib/main.js:1151:28)
    at runOnEndCallbacks (/home/projects/vitejs-vite-sdyxui/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/home/projects/vitejs-vite-sdyxui/node_modules/esbuild/lib/main.js:1149:7)
    at eval (/home/projects/vitejs-vite-sdyxui/node_modules/esbuild/lib/main.js:1258:14)
    at eval (/home/projects/vitejs-vite-sdyxui/node_modules/esbuild/lib/main.js:629:9)
    at handleIncomingPacket (/home/projects/vitejs-vite-sdyxui/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/projects/vitejs-vite-sdyxui/node_modules/esbuild/lib/main.js:596:7)
    at Socket.EventEmitter.emit (https://vitejs-vite-sdyxui.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:126633)
    at addChunk (https://vitejs-vite-sdyxui.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:508416)
```

### System Info

```shell
System:
    OS: Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: Unknown - /bin/jsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.32 => 1.0.0-next.32 
    svelte: ^3.44.0 => 3.44.3 
    vite: ^2.7.4 => 2.7.4
```

### Severity

blocking an upgrade

**Comment by bluwy** [comment]
I've tested this locally, and it doesn't seem to be related to Vite 2.7. It seems that Vite is failing to pre-bundle `@reuters-graphics/style-theme-eisbaer`, because its entrypoint is a SCSS file (Vite only handles JS or HTML-ish entrypoints). This is a `vite-plugin-svelte` bug as Vite automatically skips that package when scanning, but `vite-plugin-svelte` is explicitly adding that to handle prebundling for svelte component libraries.

I don't have a clear solution yet to tackle this, but at the meantime, a workaround of `optimizeDeps.exclude: ["@reuters-graphics/style-theme-eisbaer"]` should work.

**Comment by hobbes7878** [comment]
Ah, that does make sense. Fwiw, the same config worked fine prior to 2.7, but tested excluding our style lib and that is indeed working. Thanks very much for solving our nuance. Thought it might've been something more general, but very glad to be able to update now. I'll mark this closed. Cheers.

**Comment by bluwy** [comment]
Nice! Yeah on `vite-plugin-svelte`'s side, we could definitely improve the heuristic to avoid this kind of scenarios. I'll open it again for now so we can fix this in some way.
