### ISSUE TITLE
Experimental inspector not found by Vite

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/vite-plugin-svelte#330]
### Describe the bug

Updated to the latest version and tried to set `config.experimental.inspector` to `true` in the `svelte.config.js` file in my SvelteKit project. 

### Reproduction

Create a new skeleton SvelteKit project and set `config.experimental.inspector` to `true`

### Logs

```shell
vite:resolve 1.77ms /.svelte-kit/generated/root.svelte -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/generated/root.svelte +0ms
  vite:load 1.70ms [fs] /.svelte-kit/generated/root.svelte +0ms
  vite:vite-plugin-svelte setting cssHash s-cCKfmRoJfo02 for /.svelte-kit/generated/root.svelte +3s
  vite:vite-plugin-svelte transform returns compiled js for /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/generated/root.svelte +71ms
  vite:import-analysis 0.72ms [0 imports rewritten] .svelte-kit/generated/root.svelte +0ms
  vite:transform 74.83ms /.svelte-kit/generated/root.svelte +0ms
  vite:resolve 0.55ms /.svelte-kit/runtime/paths.js -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/runtime/paths.js +128ms
  vite:load 4.32ms [fs] /.svelte-kit/runtime/paths.js +129ms
  vite:import-analysis 0.04ms [no imports] .svelte-kit/runtime/paths.js +54ms
  vite:transform 0.48ms /.svelte-kit/runtime/paths.js +54ms
  vite:resolve 0.60ms /.svelte-kit/runtime/components/layout.svelte -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/runtime/components/layout.svelte +12ms
  vite:resolve 0.67ms /src/routes/index.svelte -> /Users/mathiaspicker/Documents/2022/my-app/src/routes/index.svelte +0ms
  vite:load 0.59ms [fs] /.svelte-kit/runtime/components/layout.svelte +9ms
  vite:vite-plugin-svelte setting cssHash s-pdl50zIt_88L for /.svelte-kit/runtime/components/layout.svelte +66ms
  vite:vite-plugin-svelte transform returns compiled js for /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/runtime/components/layout.svelte +6ms
  vite:import-analysis 0.10ms [0 imports rewritten] .svelte-kit/runtime/components/layout.svelte +15ms
  vite:transform 6.58ms /.svelte-kit/runtime/components/layout.svelte +15ms
  vite:load 7.70ms [fs] /src/routes/index.svelte +7ms
  vite:vite-plugin-svelte setting cssHash s-Uap-jPRb-uiE for /src/routes/index.svelte +1ms
  vite:vite-plugin-svelte transform returns compiled js for /Users/mathiaspicker/Documents/2022/my-app/src/routes/index.svelte +3ms
  vite:import-analysis 0.08ms [0 imports rewritten] src/routes/index.svelte +4ms
  vite:transform 3.33ms /src/routes/index.svelte +4ms
  vite:time 240.68ms / +0ms
  vite:load 1.26ms [fs] .svelte-kit/runtime/client/start.js +114ms
  vite:resolve 0.18ms svelte -> /Users/mathiaspicker/Documents/2022/my-app/node_modules/.vite/deps/svelte.js?v=b429f8ae +126ms
  vite:resolve 0.10ms /node_modules/.vite/deps/svelte.js?v=b429f8ae -> /Users/mathiaspicker/Documents/2022/my-app/node_modules/.vite/deps/svelte.js?v=b429f8ae +1ms
  vite:resolve 0.03ms svelte/store -> /Users/mathiaspicker/Documents/2022/my-app/node_modules/.vite/deps/svelte_store.js?v=b429f8ae +0ms
  vite:resolve 0.14ms /node_modules/.vite/deps/svelte_store.js?v=b429f8ae -> /Users/mathiaspicker/Documents/2022/my-app/node_modules/.vite/deps/svelte_store.js?v=b429f8ae +0ms
  vite:resolve 0.33ms ../paths.js -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/runtime/paths.js +1ms
  vite:resolve 0.49ms __GENERATED__/root.svelte -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/generated/root.svelte +1ms
  vite:resolve 0.24ms __GENERATED__/client-manifest.js -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/generated/client-manifest.js +0ms
  vite:resolve 0.16ms /.svelte-kit/generated/client-manifest.js -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/generated/client-manifest.js +1ms
  vite:resolve 0.20ms ./singletons.js -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/runtime/client/singletons.js +0ms
  vite:resolve 0.18ms /.svelte-kit/runtime/client/singletons.js -> /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/runtime/client/singletons.js +0ms
15:20:08 [vite] Internal server error: Cannot find module '@sveltejs/vite-plugin-svelte/src/ui/inspector/load-inspector.ts'
Require stack:
- /Users/mathiaspicker/Documents/2022/my-app
  Plugin: vite:import-analysis
  File: /Users/mathiaspicker/Documents/2022/my-app/.svelte-kit/runtime/client/start.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.resolve (node:internal/modules/cjs/helpers:108:19)
      at Context.resolveId (file:///Users/mathiaspicker/Documents/2022/my-app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1554:35)
      at Object.resolveId (/Users/mathiaspicker/Documents/2022/my-app/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:38898:55)
      at async TransformContext.resolve (/Users/mathiaspicker/Documents/2022/my-app/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:38672:23)
      at async normalizeUrl (/Users/mathiaspicker/Documents/2022/my-app/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:56884:34)
      at async TransformContext.transform (/Users/mathiaspicker/Documents/2022/my-app/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:57039:57)
      at async Object.transform (/Users/mathiaspicker/Documents/2022/my-app/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:38961:30)
      at async doTransform (/Users/mathiaspicker/Documents/2022/my-app/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:55918:29)
  vite:time 30.07ms .svelte-kit/runtime/client/start.js +121ms
  vite:time 1.53ms /favicon.png +22ms
```

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 43.46 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.54
    Edge: 101.0.1210.39
    Firefox: 99.0.1
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.40 
    @sveltejs/kit: next => 1.0.0-next.326 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

blocking an upgrade

**Comment by dominikg** [comment]
hmm, had something similar happen on stackblitz but thought it was happening due to their webcontainer https://github.com/stackblitz/webcontainer-core/issues/693 

which package manager do you use?

**Comment by MathiasWP** [comment]
I use npm @dominikg

**Comment by dominikg** [comment]
thanks, can confirm this happening with npm on my machine too.

**Comment by dominikg** [comment]
Looks like createRequire + resolve works differently. 
Solution could be to use this.require to get local plugin path once and then use abs path to load inspector instead of virtual ids.

**Comment by MathiasWP** [comment]
Is this something that could be implemented soon? This feature is amazing, and I'll happily test it and help making this a stable feature.

**Comment by dominikg** [comment]
@MathiasWP to help with testing,   you can check out the branch of  #332 , run `pnpm install && pnpm build` to build the plugin and then link  `@sveltejs/vite-plugin-svelte`  to `<checkout-dir>/packages/vite-plugin-svelte` in the project you're having this issue.

**Comment by MathiasWP** [comment]
@dominikg I'll gladly help! I struggling with my `pnpm` version being different than the one specified in `package.json`, and I'm not that familiar with `pnpm`. Do you have any tips on how to solve this issue:

![Screenshot 2022-05-11 at 16 46 45](https://user-images.githubusercontent.com/48158184/167878457-1a44734c-8c85-4ec0-8c2c-d6187cf8707c.png)
?

**Comment by MathiasWP** [comment]
The fix worked, @dominikg!

<img width="493" alt="Screenshot 2022-05-11 at 18 46 27" src="https://user-images.githubusercontent.com/48158184/167903690-9f86aaf7-c471-4e44-afb0-4dae23ee1965.png">

**Comment by dominikg** [comment]
fix released in 1.0.0-next.44

**Comment by lukaszpolowczyk** [comment]
> The fix worked

@MathiasWP What can be done to make the inspector work?
Can you show the entire configuration file?
@sveltejs/kit v1.0.0-next.390

**Comment by MathiasWP** [comment]
> > The fix worked
> 
> @MathiasWP What can be done to make the inspector work? Can you show the entire configuration file? @sveltejs/kit v1.0.0-next.390

Sure!

```ts
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [preprocess()],
	experimental: {
		// https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#inspector
		inspector: true
	}
}
```

**Comment by lukaszpolowczyk** [comment]
@MathiasWP I don't understand. It doesn't work for me.
Is doing like this:
```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```
And after that adding:
```
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [preprocess()],
	experimental: {
		// https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#inspector
		inspector: true
	}
}
```

Should it work already?
Does anything else need to be done?

I also tried with this, and it doesn't work either:
```
npm create vite@latest my-app -- [--template svelte](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-svelte)
cd my-app
npm install
npm run dev
```

One can become stupid from this. :confused:

**Comment by MathiasWP** [comment]
@lukaszpolowczyk setting `experimental.inspector` in the config should be enough. Note that you need to enable with your keyboard: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#inspector

**Comment by bluwy** [comment]
> Error: Invalid options in svelte config. Move the following options into 'vitePlugin:{...}': experimental

You need to set `config.vitePlugin.experimental.inspector` instead. This breaking change was made in 1.0.0 and is documented at https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#experimental-options

**Comment by lukaszpolowczyk** [comment]
@bluwy Thanks, it works. Phew.
All this time I didn't know what the fault was, I tried other options before, I didn't know if it was the fault of the configuration or the shortcut or something else.
It turns out that both the shortcut and the configuration in part....

The best example to test that everything works:
```javascript
import adapter from '@sveltejs/adapter-auto';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter()
	},
	vitePlugin: {
		experimental: {
			inspector: {
				showToggleButton: "always"
			}
		}
	}
};

export default config;

```

The only distracting downside - VSCode reports problems:
```
Type '{ kit: { adapter: Adapter; prerender: { default: true; }; browser: { router: false; }; }; vitePlugin: { experimental: { inspector: { showToggleButton: string; }; }; }; }' is not assignable to type 'Config'.
  Object literal may only specify known properties, and 'vitePlugin' does not exist in type 'Config'.
```
But it still works.
