### ISSUE TITLE
[vite3] difference in ssr externalizaion during dev

### ISSUE THREAD

**Issue by dominikg** [sveltejs/vite-plugin-svelte#365]
### Describe the bug

In vite3, dependencies are treated differently in ssr dev. Due to that, libraries that have svelte as a dependency or peer dependency but do not contain svelte components or a "svelte" field in package.json need to be added to ssr.noExternal as well, otherwise deduplication of `svelte` fails and we get a runtime error.

### Reproduction

comment noExternal config in https://github.com/sveltejs/vite-plugin-svelte/blob/vite-3/packages/e2e-tests/kit-node/svelte.config.js#L14 and run `rm -rf node_modules/.vite && pnpm dev` in `kit-node`

### Logs

```shell
Function called outside component initialization
Error: Function called outside component initialization
    at get_current_component (file:///home/dominikg/develop/sveltejs/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.mjs:953:15)
    at setContext (file:///home/dominikg/develop/sveltejs/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.mjs:985:5)
    at Proxy.setSomeContext (file:///home/dominikg/develop/sveltejs/vite-plugin-svelte/packages/e2e-tests/_test_dependencies/svelte-api-only/index.js:4:2)
    at index.svelte:35:1
    at Object.$$render (/home/dominikg/develop/sveltejs/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
    at Object.default (root.svelte:43:39)
    at eval (/.svelte-kit/runtime/components/layout.svelte:8:41)
    at Object.$$render (/home/dominikg/develop/sveltejs/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
    at root.svelte:37:37
    at $$render (/home/dominikg/develop/sveltejs/vite-plugin-svelte/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/internal/index.js:1758:22)
```

### System Info

```shell
-
```

### Severity

blocking an upgrade

**Comment by dominikg** [comment]
fixed in https://github.com/sveltejs/vite-plugin-svelte/pull/359/commits/66ae0ed736356fbb23bb2bebaa945f8d5bf42a52
