### ISSUE TITLE
new Vite build system: no output, but vite says sompleted

### ISSUE THREAD

**Issue by skamansam** [sveltejs/vite-plugin-svelte#386]
### Describe the bug

When i try to build under the new vite plugin, no output is generated. I migrated from a pre-vite build system and everything worked well. `vite dev` works well, and `svelte-check` has no errors. There are some dependency issues, but they were not a problem before. I am unsure whether this is a vite-plugin-svelte issue or one with vite, but it appears to be the former based on the debug output.

### Reproduction

My repo is at https://github.com/skamansam/skamansam.github.io/ . make sure it is the `svelte` branch

### Logs

```shell
[sam@rbe skamansam.github.io]$ pnpm build --debug

> skamansam.github.io@0.0.1 build /home/sam/workspace/skamansam.github.io
> vite build "--debug"

  vite:vite-plugin-svelte svelte inspector path: /home/sam/workspace/skamansam.github.io/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.49_svelte@3.49.0+vite@2.9.14/node_modules/@sveltejs/vite-plugin-svelte/src/ui/inspector/ +0ms
  vite:config native esm config loaded in 136.96ms URL {
  href: 'file:///home/sam/workspace/skamansam.github.io/vite.config.js',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/home/sam/workspace/skamansam.github.io/vite.config.js',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
} +0ms
  vite:vite-plugin-svelte findSvelteDependencies: searching svelte dependencies in /home/sam/workspace/skamansam.github.io +571ms
  vite:vite-plugin-svelte dependency remark-emoji does not export package.json Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/sam/workspace/skamansam.github.io/node_modules/remark-emoji/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at resolveDependencyData (file:///home/sam/workspace/skamansam.github.io/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.49_svelte@3.49.0+vite@2.9.14/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:632:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
} +7ms
  vite:vite-plugin-svelte dependency remark-preview does not export package.json Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/sam/workspace/skamansam.github.io/node_modules/remark-preview/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at resolveDependencyData (file:///home/sam/workspace/skamansam.github.io/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.49_svelte@3.49.0+vite@2.9.14/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:632:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
} +3ms
  vite:vite-plugin-svelte additional vite config {
  resolve: {
    mainFields: [ 'svelte', 'module', 'jsnext:main', 'jsnext' ],
    dedupe: [
      'svelte/animate',
      'svelte/easing',
      'svelte/internal',
      'svelte/motion',
      'svelte/ssr',
      'svelte/store',
      'svelte/transition',
      'svelte',
      'svelte-hmr/runtime/hot-api-esm.js',
      'svelte-hmr/runtime/proxy-adapter-dom.js',
      'svelte-hmr'
    ]
  },
  ssr: {
    noExternal: [ '@steeze-ui/svelte-icon', '@svelte-web-fonts/google' ]
  }
} +4ms
  vite:vite-plugin-svelte Setting compilerOptions.hydratable: true for SvelteKit +72ms
  vite:vite-plugin-svelte resolved options {
  hot: false,
  compilerOptions: { css: false, dev: false, hydratable: true },
  extensions: [ '.svelte', '.svelte.md', '.md', '.svx', '.mdx' ],
  emitCss: true,
  preprocess: [
    {
      defaultLanguages: [Object],
      markup: [AsyncFunction: markup],
      script: [AsyncFunction: script],
      style: [AsyncFunction: style]
    },
    { markup: [AsyncFunction: markup] }
  ],
  kit: {
    adapter: { name: '@sveltejs/adapter-static', adapt: [AsyncFunction: adapt] },
    prerender: { default: true }
  },
  configFile: '/home/sam/workspace/skamansam.github.io/svelte.config.js',
  root: '/home/sam/workspace/skamansam.github.io',
  isBuild: true,
  isServe: false,
  isDebug: true,
  isProduction: true
} +1ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:build-metadata',
  vite:config     'alias',
  vite:config     'vite-plugin-svelte',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite-plugin-svelte-kit',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:build-html',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:watch-package-data',
  vite:config     'commonjs',
  vite:config     'vite:data-uri',
  vite:config     'rollup-plugin-dynamic-import-variables',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:esbuild-transpile',
  vite:config     'vite:terser',
  vite:config     'vite:manifest',
  vite:config     'vite:reporter',
  vite:config     'vite:load-fallback'
  vite:config   ],
  vite:config   build: {
  vite:config     target: [ 'es2019', 'edge88', 'firefox78', 'chrome87', 'safari13.1' ],
  vite:config     polyfillModulePreload: true,
  vite:config     outDir: '/home/sam/workspace/skamansam.github.io/.svelte-kit/output/client/_app',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     cssTarget: [ 'es2019', 'edge88', 'firefox78', 'chrome87', 'safari13.1' ],
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {
  vite:config       input: [Object],
  vite:config       output: [Object],
  vite:config       preserveEntrySignatures: 'strict'
  vite:config     },
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     manifest: true,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     polyfillDynamicImport: false,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] }
  vite:config   },
  vite:config   resolve: {
  vite:config     dedupe: [
  vite:config       'svelte/animate',
  vite:config       'svelte/easing',
  vite:config       'svelte/internal',
  vite:config       'svelte/motion',
  vite:config       'svelte/ssr',
  vite:config       'svelte/store',
  vite:config       'svelte/transition',
  vite:config       'svelte',
  vite:config       'svelte-hmr/runtime/hot-api-esm.js',
  vite:config       'svelte-hmr/runtime/proxy-adapter-dom.js',
  vite:config       'svelte-hmr'
  vite:config     ],
  vite:config     mainFields: [ 'svelte', 'module', 'jsnext:main', 'jsnext' ],
  vite:config     alias: [ [Object], [Object], [Object], [Object], [Object] ]
  vite:config   },
  vite:config   ssr: {
  vite:config     noExternal: [ '@steeze-ui/svelte-icon', '@svelte-web-fonts/google' ]
  vite:config   },
  vite:config   base: '/_app/',
  vite:config   publicDir: '',
  vite:config   configFile: '/home/sam/workspace/skamansam.github.io/vite.config.js',
  vite:config   configFileDependencies: [ '/home/sam/workspace/skamansam.github.io/vite.config.js' ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     build: {}
  vite:config   },
  vite:config   root: '/home/sam/workspace/skamansam.github.io',
  vite:config   cacheDir: '/home/sam/workspace/skamansam.github.io/node_modules/.vite',
  vite:config   command: 'build',
  vite:config   mode: 'production',
  vite:config   isWorker: false,
  vite:config   isProduction: true,
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] }
  vite:config   },
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   env: {
  vite:config     VITE_SVELTEKIT_APP_VERSION: '1657510493350',
  vite:config     VITE_SVELTEKIT_APP_VERSION_FILE: '_app/version.json',
  vite:config     VITE_SVELTEKIT_APP_VERSION_POLL_INTERVAL: '0',
  vite:config     BASE_URL: '/_app/',
  vite:config     MODE: 'production',
  vite:config     DEV: false,
  vite:config     PROD: true
  vite:config   },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) { set: [Function (anonymous)] },
  vite:config   createResolver: [Function: createResolver],
  vite:config   optimizeDeps: {
  vite:config     esbuildOptions: { keepNames: undefined, preserveSymlinks: undefined }
  vite:config   },
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object]
  vite:config     ],
  vite:config     rollupOptions: {}
  vite:config   }
  vite:config } +658ms
vite v2.9.14 building for production...
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/routes/__layout.svelte +518ms
transforming (1) src/routes/__layout.svelte  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/routes/__error.svelte +283ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/routes/categories/[category].svelte +129ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/routes/index.svelte +209ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/routes/portfolio/index.svelte +66ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/routes/posts/index.svelte +535ms
transforming (7) src/routes/posts/index.svelte  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/routes/tags/[tag].svelte +42ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/components/Sidebar.svelte +111ms
  vite:vite-plugin-svelte resolveId resolved /home/sam/workspace/skamansam.github.io/node_modules/.pnpm/@steeze-ui+svelte-icon@1.3.1/node_modules/@steeze-ui/svelte-icon/index.js via package.json svelte field of @steeze-ui/svelte-icon +12ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/components/Footer.svelte +26ms
transforming (13) node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/index.mjs  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/.svelte-kit/generated/root.svelte +352ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/components/Card.svelte +146ms
transforming (24) .svelte-kit/generated/client-matchers.js  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/node_modules/.pnpm/@steeze-ui+svelte-icon@1.3.1/node_modules/@steeze-ui/svelte-icon/Icon.svelte +326ms
  vite:resolve 0.53ms ../node_modules/prism-themes/themes/prism-synthwave84.css -> /home/sam/workspace/skamansam.github.io/node_modules/.pnpm/prism-themes@1.9.0/node_modules/prism-themes/themes/prism-synthwave84.css +0ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/components/Header.svelte +775ms
transforming (26) src/components/Header.svelte  vite:vite-plugin-svelte resolveId resolved /home/sam/workspace/skamansam.github.io/node_modules/.pnpm/@steeze-ui+svelte-icon@1.3.1/node_modules/@steeze-ui/svelte-icon/index.js via package.json svelte field of @steeze-ui/svelte-icon +12ms
  vite:vite-plugin-svelte transform returns compiled js for /home/sam/workspace/skamansam.github.io/src/routes/posts/2008-05-09-wxcpan-skeleton-code.md +43ms
✓ 27 modules transformed.
```
```


### System Info

```shell
System:
    OS: Linux 5.18 Fedora Linux 36 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
    Memory: 2.48 GB / 15.51 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.9.1 - ~/.config/nvm/versions/node/v17.9.1/bin/node
    npm: 8.11.0 - ~/.config/nvm/versions/node/v17.9.1/bin/npm
  Browsers:
    Brave Browser: beta
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.55 
    @sveltejs/adapter-static: 1.0.0-next.34 => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.367 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^2.9.14 => 2.9.14
```

### Severity

blocking an upgrade

**Comment by bluwy** [comment]
This isn't an issue in `vite-plugin-svelte`, but SvelteKit. For support, please open a [discussion](https://github.com/sveltejs/kit/discussions) instead unless a minimal repro is provided.
