### ISSUE TITLE
Broken library mode

### ISSUE THREAD

**Issue by bryanmylee** [sveltejs/vite-plugin-svelte#425]
### Describe the bug

I'm using Vite to build a Svelte component library. However, when testing the package on an example repo, I get the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading '$$')
    at q (main.js?t=1661908450733:247:25)
    at new vt (main.js?t=1661908450733:644:14)
    at create_fragment (App.svelte:14:70)
    at init (index.mjs:1906:37)
    at new App (App.svelte:34:79)
    at createProxiedComponent (svelte-hooks.js:341:9)
    at new ProxyComponent (proxy.js:242:7)
    at new Proxy<App> (proxy.js:349:11)
    at main.ts:4:13
```

I've built working Svelte component libraries with SvelteKit before but given its instability, I'd rather stick with plain Vite.

### Reproduction

https://github.com/bryanmylee/vite-svelte-library-mode

The reproduction is based on [`@ally-ui/svelte-dialog@0.0.11`](https://github.com/ally-ui/ally-ui/tree/main/packages/dialog/svelte) which is built with Vite's library mode.

Install the dependencies and run `npm run dev` to see the error in the example application.

### Logs

```shell
### Browser


proxy.js:15 [HMR][Svelte] Unrecoverable HMR error in <App>: next update will trigger a full reload
logError @ proxy.js:15
Proxy<App> @ proxy.js:380
(anonymous) @ main.ts:4
main.js:247 Uncaught TypeError: Cannot read properties of undefined (reading '$$')
    at q (main.js:247:25)
    at new vt2 (main.js:644:14)
    at create_fragment (App.svelte? [sm]:14:70)
    at init (index.mjs:1906:37)
    at new App (App.svelte? [sm]:34:79)
    at createProxiedComponent (svelte-hooks.js:341:9)
    at new ProxyComponent (proxy.js:242:7)
    at new Proxy<App> (proxy.js:349:11)
    at main.ts:4:13
```

### Server

```
vite:vite-plugin-svelte svelte inspector path: /Users/bryan/Projects/web/repros/vite-svelte-library-mode/node_modules/@sveltejs/vite-plugin-svelte/src/ui/inspector/ +0ms
  vite:config bundled config file loaded in 111.93ms +0ms
  vite:vite-plugin-svelte findSvelteDependencies: searching svelte dependencies in /Users/bryan/Projects/web/repros/vite-svelte-library-mode +12ms
  vite:vite-plugin-svelte dependency @ally-ui/svelte-dialog does not export package.json Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/bryan/Projects/web/repros/vite-svelte-library-mode/node_modules/@ally-ui/svelte-dialog/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:748:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at resolveDependencyData (file:///Users/bryan/Projects/web/repros/vite-svelte-library-mode/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:639:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
} +2ms
  vite:vite-plugin-svelte adding bare svelte packages to optimizeDeps.include: svelte/animate, svelte/easing, svelte/internal, svelte/motion, svelte/store, svelte/transition, svelte  +3ms
  vite:vite-plugin-svelte automatically excluding found svelte dependencies:  +0ms
  vite:vite-plugin-svelte reincluding transitive dependencies of excluded svelte dependencies [] +0ms
  vite:vite-plugin-svelte additional vite config {
  resolve: {
    mainFields: [ 'svelte', 'module', 'jsnext:main', 'jsnext' ],
    dedupe: [
      'svelte/animate',
      'svelte/easing',
      'svelte/internal',
      'svelte/motion',
      'svelte/ssr',
      'svelte/store',
      'svelte/transition',
      'svelte',
      'svelte-hmr/runtime/hot-api-esm.js',
      'svelte-hmr/runtime/proxy-adapter-dom.js',
      'svelte-hmr'
    ]
  },
  optimizeDeps: {
    include: [
      'svelte/animate',
      'svelte/easing',
      'svelte/internal',
      'svelte/motion',
      'svelte/store',
      'svelte/transition',
      'svelte'
    ],
    exclude: [ 'svelte-hmr' ]
  },
  ssr: {
    noExternal: [ 'svelte', /^svelte\//, '@ally-ui/svelte-dialog' ],
    external: [ '@ally-ui/core-dialog', '@ally-ui/svelte' ]
  }
} +0ms
  vite:vite-plugin-svelte resolved options {
  hot: { injectCss: false },
  compilerOptions: { css: false, dev: true },
  extensions: [ '.svelte' ],
  emitCss: true,
  preprocess: [
    {
      defaultLanguages: [Object],
      markup: [AsyncFunction: markup],
      script: [AsyncFunction: script],
      style: [AsyncFunction: style]
    },
    { style: [Function: style] }
  ],
  configFile: '/Users/bryan/Projects/web/repros/vite-svelte-library-mode/svelte.config.js',
  root: '/Users/bryan/Projects/web/repros/vite-svelte-library-mode',
  isBuild: false,
  isServe: true,
  isDebug: true,
  isProduction: false
} +7ms
  vite:vite-plugin-svelte inspector disabled, could not find config +1ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite-plugin-svelte',
  vite:config     'vite-plugin-svelte:inspector',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:optimized-deps',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite:client-inject',
  vite:config     'vite:import-analysis'
  vite:config   ],
  vite:config   optimizeDeps: {
  vite:config     disabled: 'build',
  vite:config     force: undefined,
  vite:config     include: [
  vite:config       'svelte/animate',
  vite:config       'svelte/easing',
  vite:config       'svelte/internal',
  vite:config       'svelte/motion',
  vite:config       'svelte/store',
  vite:config       'svelte/transition',
  vite:config       'svelte'
  vite:config     ],
  vite:config     exclude: [ 'svelte-hmr' ],
  vite:config     esbuildOptions: { preserveSymlinks: undefined }
  vite:config   },
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] }
  vite:config   },
  vite:config   resolve: {
  vite:config     mainFields: [ 'svelte', 'module', 'jsnext:main', 'jsnext' ],
  vite:config     dedupe: [
  vite:config       'svelte/animate',
  vite:config       'svelte/easing',
  vite:config       'svelte/internal',
  vite:config       'svelte/motion',
  vite:config       'svelte/ssr',
  vite:config       'svelte/store',
  vite:config       'svelte/transition',
  vite:config       'svelte',
  vite:config       'svelte-hmr/runtime/hot-api-esm.js',
  vite:config       'svelte-hmr/runtime/proxy-adapter-dom.js',
  vite:config       'svelte-hmr'
  vite:config     ],
  vite:config     alias: [ [Object], [Object] ]
  vite:config   },
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     noExternal: [ 'svelte', /^svelte\//, '@ally-ui/svelte-dialog' ],
  vite:config     external: [ '@ally-ui/core-dialog', '@ally-ui/svelte' ],
  vite:config     optimizeDeps: { disabled: true, esbuildOptions: [Object] }
  vite:config   },
  vite:config   configFile: '/Users/bryan/Projects/web/repros/vite-svelte-library-mode/vite.config.ts',
  vite:config   configFileDependencies: [
  vite:config     '/Users/bryan/Projects/web/repros/vite-svelte-library-mode/vite.config.ts'
  vite:config   ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     optimizeDeps: { force: undefined },
  vite:config     server: {}
  vite:config   },
  vite:config   root: '/Users/bryan/Projects/web/repros/vite-svelte-library-mode',
  vite:config   base: '/',
  vite:config   publicDir: '/Users/bryan/Projects/web/repros/vite-svelte-library-mode/public',
  vite:config   cacheDir: '/Users/bryan/Projects/web/repros/vite-svelte-library-mode/node_modules/.vite',
  vite:config   command: 'serve',
  vite:config   mode: 'development',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: false,
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari13' ],
  vite:config     polyfillModulePreload: true,
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari13' ],
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {},
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     manifest: false,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] }
  vite:config   },
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   env: { BASE_URL: '/', MODE: 'development', DEV: true, PROD: false },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) {},
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:optimized-deps',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:config       'vite:css-post',
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob',
  vite:config       'vite:client-inject',
  vite:config       'vite:import-analysis'
  vite:config     ],
  vite:config     rollupOptions: {}
  vite:config   },
  vite:config   appType: 'spa',
  vite:config   experimental: { importGlobRestoreExtension: false, hmrPartialAccept: false }
  vite:config } +26ms
  vite:deps Hash is consistent. Skipping. Use --force to override. +0ms

  VITE v3.0.9  ready in 303 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
```
```


### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 56.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 98.0.2
    Safari: 15.6.1
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.1 => 1.0.2 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.7 => 3.0.9
```
```


### Severity

blocking all usage of vite-plugin-svelte

**Comment by Conduitry** [comment]
You should publish the uncompiled Svelte components as part of your package and have a `"svelte"` field in your package.json that points to a re-export of these. I don't know that this is the sole cause of this specific error, but in general, if you don't do this, then consuming Svelte projects get an already-compiled version of your Svelte components, which leads to problems because there are two different copies of the Svelte runtime code going at once.

**Comment by bryanmylee** [comment]
@Conduitry Thank you, that makes perfect sense. I thought externalizing the `svelte` dependency would prevent the issue with consuming two Svelte runtimes, but in hindsight the compilation step probably ties the components to Svelte.

I'll close this issue for now.
