### ISSUE TITLE
Hydratable Error on `vite dev`

### ISSUE THREAD

**Issue by wolfiex** [sveltejs/vite-plugin-svelte#455]
### Describe the bug

Upgrading the code to run with the latest sveltekit presents the following error from the plugin. 

```
error when starting dev server:
TypeError: Cannot read properties of null (reading 'hydratable')
    at addSvelteKitOptions (file:///  -----  /node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1345:33)
    at resolveOptions (file:/// ----- node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1265:3)

```

### Reproduction

The error from a `vite dev` command. The repo in question can be shared privately on request.

### Logs

```shell
....
  vite:esbuild init tsconfck (root: /---path---) +0ms
  vite:esbuild init tsconfck (root: /---path---) +0ms
error when starting dev server:
TypeError: Cannot read properties of null (reading 'hydratable')
    at addSvelteKitOptions (file:///---path---/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1345:33)
    at resolveOptions (file:///---path---/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1265:3)
    at configResolved (file:///---path---/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1881:19)
    at file:///---path---/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63241:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///---path---/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63241:14)
    at async createServer (file:///---path---/node_modules/vite/dist/node/chunks/dep-557f29e6.js:62063:20)
    at async CAC.<anonymous> (file:///---path---/node_modules/vite/dist/node/cli.js:700:24)
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 32.20 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.9.0 - ~/opt/miniconda3/bin/node
    npm: 8.5.5 - ~/opt/miniconda3/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Chrome: 105.0.5195.125
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.78 => 1.0.0-next.78 
    @sveltejs/adapter-node: ^1.0.0-next.95 => 1.0.0-next.95 
    @sveltejs/adapter-static: ^1.0.0-next.43 => 1.0.0-next.43 
    @sveltejs/adapter-vercel: ^1.0.0-next.77 => 1.0.0-next.77 
    @sveltejs/kit: ^1.0.0-next.350 => 1.0.0-next.503 
    svelte: ^3.29.0 => 3.50.1 
    vite: ^3.1.3 => 3.1.3
```

### Severity

blocking all usage of vite-plugin-svelte

**Comment by wolfiex** [comment]
Add `  compilerOptions: {hydrate: true}` in the config section of svelte config.

**Comment by wolfiex** [comment]
I may have spoken too early

**Comment by dominikg** [comment]
Please add a link to a public and minimal reproduction.

**Comment by dominikg** [comment]
@wolfiex closing this until you are able to provide a public reproduction.
