### ISSUE TITLE
Supported Svelte versions

### ISSUE THREAD

**Issue by Marr11317** [sveltejs/vite-plugin-svelte#46]
## Description

Which svelte versions are supported? Running with svelte 3.0.x doesn't work.

```
11:00:04 PM [vite] Internal server error: Unrecognized option 'cssHash'
  Plugin: vite-plugin-svelte
  File: /workspaces/vite-plugin-components/examples/svelte3/src/App.svelte
      at /workspaces/vite-plugin-components/node_modules/.pnpm/svelte@3.12.1/node_modules/svelte/compiler.js:23906:20
      at Array.forEach (<anonymous>)
      at validate_options (/workspaces/vite-plugin-components/node_modules/.pnpm/svelte@3.12.1/node_modules/svelte/compiler.js:23900:27)
      at compile (/workspaces/vite-plugin-components/node_modules/.pnpm/svelte@3.12.1/node_modules/svelte/compiler.js:23926:6)
      at compileSvelte (/workspaces/vite-plugin-components/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.10_svelte@3.12.1+vite@2.3.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:244:48)
      at async TransformContext.transform (/workspaces/vite-plugin-components/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.10_svelte@3.12.1+vite@2.3.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:837:27)
      at async Object.transform (/workspaces/vite-plugin-components/node_modules/.pnpm/vite@2.3.3/node_modules/vite/dist/node/chunks/dep-e9a16784.js:44268:30)
      at async transformRequest (/workspaces/vite-plugin-components/node_modules/.pnpm/vite@2.3.3/node_modules/vite/dist/node/chunks/dep-e9a16784.js:58540:29)
      at async viteTransformMiddleware (/workspaces/vite-plugin-components/node_modules/.pnpm/vite@2.3.3/node_modules/vite/dist/node/chunks/dep-e9a16784.js:58678:32) (x2)
```

## Reproduction

[This branch in this repo](https://github.com/Marr11317/vite-plugin-components/blob/support-3.0/examples/svelte3/package.json) shows the problem.

**Comment by dominikg** [comment]
see peer dep  
https://github.com/sveltejs/vite-plugin-svelte/blob/93ca647767c683d9f8996e670ae5c1b8171adc21/packages/vite-plugin-svelte/package.json#L45

cssHash option is required for css hmr. you may be able to use it with setting `emitCss: false` during dev,  but versions older than peer dep are not officially supported by vite-plugin-svelte.
