### ISSUE TITLE
[vite-plugin-svelte] Cannot read properties of undefined (reading 'add') (Windows only?)

### ISSUE THREAD

**Issue by ryanbas21** [sveltejs/vite-plugin-svelte#500]
### Describe the bug

I have been experiencing this error on windows builds in Github actions only. The builds are fine locally (macos) and in CI (macos and ubuntu) but the windows builds throw this error.

### Reproduction URL

https://github.com/cerebrl/forgerock-web-login-framework/actions/runs/3481210308/jobs/5822086806

### Reproduction

Feel free to look at the CI here, its the only way to reproduce as I dont have a windows OS to test this on myself. I see a few versions of rollup installed when I `npm ls`

### Logs

```shell
most of which are de-duped but `vitest` and `vite` have slightly different versions. This could be nothing but i'm trying to debug this myself and rollup seems to be the only thing that is in the call stack.


├─┬ @rollup/plugin-alias@3.1.9
│ └── rollup@2.78.1 deduped
├─┬ @rollup/plugin-commonjs@22.0.2
│ ├─┬ @rollup/pluginutils@3.1.0
│ │ └── rollup@2.78.1 deduped
│ └── rollup@2.78.1 deduped
├─┬ @rollup/plugin-json@4.1.0
│ └── rollup@2.78.1 deduped
├─┬ @rollup/plugin-node-resolve@13.3.0
│ └── rollup@2.78.1 deduped
├─┬ @rollup/plugin-typescript@8.3.4
│ └── rollup@2.78.1 deduped
├─┬ @sveltejs/adapter-node@1.0.0-next.100
│ ├─┬ @rollup/plugin-commonjs@23.0.2
│ │ ├─┬ @rollup/pluginutils@5.0.2
│ │ │ └── rollup@2.79.1 deduped
│ │ └── rollup@2.79.1 deduped
│ ├─┬ @rollup/plugin-json@5.0.1
│ │ └── rollup@2.79.1 deduped
│ ├─┬ @rollup/plugin-node-resolve@15.0.1
│ │ └── rollup@2.79.1 deduped
│ └── rollup@2.79.1
├─┬ rollup-plugin-svelte@7.1.0
│ └── rollup@2.78.1 deduped
├─┬ rollup-plugin-terser@7.0.2
│ └── rollup@2.78.1 deduped
├── rollup@2.78.1
├─┬ vite@3.1.0
│ └── rollup@2.78.1 deduped
└─┬ vitest@0.16.0
  └─┬ vite@2.9.15
    └── rollup@2.77.3
```

The error itself:

```
✓ 95 modules transformed.
file: D:/a/forgerock-web-login-framework/forgerock-web-login-framework/src/routes/(app)/+layout.svelte
error during build:
TypeError: Cannot read properties of undefined (reading 'add')
    at ensureWatchedFile (file:///D:/a/forgerock-web-login-framework/forgerock-web-login-framework/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1647:13)
    at file:///D:/a/forgerock-web-login-framework/forgerock-web-login-framework/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1972:13
    at Array.forEach (<anonymous>)
    at Object.transform (file:///D:/a/forgerock-web-login-framework/forgerock-web-login-framework/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1971:36)
    at async transform (file:///D:/a/forgerock-web-login-framework/forgerock-web-login-framework/node_modules/rollup/dist/es/shared/rollup.js:21928:16)
    at async ModuleLoader.addModuleSource (file:///D:/a/forgerock-web-login-framework/forgerock-web-login-framework/node_modules/rollup/dist/es/shared/rollup.js:22153:30)
Error: Process completed with exit code 1.
```
```


### System Info

```shell
I'm on a mac but it is fine locally, CI is where i see this. So windows?
```

**Comment by Conduitry** [comment]
CI on macOS is failing as well in the logs you linked to.

We do need a minimal reproduction though, and not a link to your entire test suite running.

**Comment by ryanbas21** [comment]
> CI on macOS is failing as well in the logs you linked to.
> 
> We do need a minimal reproduction though, and not a link to your entire test suite running.

Yeah the mac os fail is unrelated to this issue, mac builds, just has a playwright failure.  i can try to spin up just a windows instance of this i guess.

**Comment by dominikg** [comment]
> If no reproduction is provided, the issue will be closed.

@ryanbas21  if you are able to reproduce the issue and provide the reproduction url, the issue can be reopened later.
