### ISSUE TITLE
vite-plugin-svelte errors out after upgrading to 2.0.0

### ISSUE THREAD

**Issue by eswat2** [sveltejs/vite-plugin-svelte#540]
### Describe the bug

Updating a simple project to the latest vite & vite-plugin-svelte fails to build...

my vite.config.js is here:
```
import { defineConfig } from "vite"
import { svelte } from "@sveltejs/vite-plugin-svelte"

export default defineConfig({
  plugins: [svelte({})],
})
```

➜  tinker-s4e git:(main) ncu -u
Using yarn
Upgrading /Users/richardhess/github/svelte/tinker-s4e/package.json
[====================] 12/12 100%

 @sveltejs/vite-plugin-svelte  1.4.0  →  2.0.0
 vite                          3.2.5  →  4.0.0

Run yarn install to install new versions.
➜  tinker-s4e git:(main) ✗ yarn
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 2.32s.
➜  tinker-s4e git:(main) ✗ yarn build
yarn run v1.22.19
$ yarn twx; yarn format; vite build
$ sh ./.generate
-- src/utils/tw-version.js
-- tinker-s4e

Rebuilding...

Done in 81ms.
$ prettier --write './src/**/*.{css,pcss,js,svelte}'
src/App.svelte 98ms
src/components/Bar.svelte 48ms
src/components/ColorPicker.svelte 37ms
src/components/Eswat2.svelte 21ms
src/components/Sampler.svelte 25ms
src/components/TwLabel.svelte 11ms
src/components/Values.svelte 18ms
src/icons/ChevronDoubleLeft.svelte 21ms
src/icons/Close.svelte 23ms
src/icons/Fingerprint.svelte 24ms
src/icons/Radio.svelte 28ms
src/icons/Refresh.svelte 23ms
src/main.js 4ms
src/styles/app.css 22ms
src/styles/input.pcss 8ms
src/utils/funnelDefs.js 6ms
src/utils/index.js 4ms
src/utils/namedColors.js 7ms
src/utils/stores.js 7ms
src/utils/tw-version.js 4ms
✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@sveltejs/vite-plugin-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@sveltejs/vite-plugin-svelte" package

    node_modules/esbuild/lib/main.js:1352:27:
      1352 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///Users/richardhess/github/svelte/tinker-s4e/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:22933:11)
    at resolvePackageEntry (file:///Users/richardhess/github/svelte/tinker-s4e/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:22928:9)
    at tryNodeResolve (file:///Users/richardhess/github/svelte/tinker-s4e/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:22668:20)
    at file:///Users/richardhess/github/svelte/tinker-s4e/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:63027:40
    at requestCallbacks.on-resolve (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:1352:28)
    at handleRequest (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:720:19)
    at handleIncomingPacket (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:742:7)
    at Socket.readFromStdout (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:670:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1276:20:
      1276 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/richardhess/github/svelte/tinker-s4e/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:63016:27)
    at handlePlugins (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:1276:21)
    at buildOrServeImpl (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:965:5)
    at Object.buildOrServe (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:773:5)
    at /Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:2112:17
    at new Promise (<anonymous>)
    at Object.build (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:2111:14)
    at build (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:1958:51)
    at bundleConfigFile (file:///Users/richardhess/github/svelte/tinker-s4e/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:62980:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.js:2:23:
      2 │ import { svelte } from "@sveltejs/vite-plugin-svelte"
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /Users/richardhess/github/svelte/tinker-s4e/vite.config.js
error during build:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1352:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@sveltejs/vite-plugin-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@sveltejs/vite-plugin-svelte" package
    at failureErrorWithLog (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:1591:15)
    at /Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:1047:28
    at runOnEndCallbacks (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:1463:61)
    at buildResponseToResult (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:1045:7)
    at /Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:1157:14
    at responseCallbacks.<computed> (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:694:9)
    at handleIncomingPacket (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:749:9)
    at Socket.readFromStdout (/Users/richardhess/github/svelte/tinker-s4e/node_modules/esbuild/lib/main.js:670:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproduction URL

https://github.com/eswat2/tinker-s4e

### Reproduction

1. update dependencies using `ncu -u`
2. yarn
3. yarn build
4. error...

### System Info

```shell
➜  tinker-s4e git:(main) ✗ npx envinfo --system --binaries --browsers --npmPackages "{svelte,svelte-hmr,@sveltejs/*,vite}"
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 269.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Chrome Canary: 110.0.5467.0
    Edge: 108.0.1462.46
    Firefox: 107.0
    Firefox Developer Edition: 108.0
    Safari: 16.1
  npmPackages:
    @sveltejs/vite-plugin-svelte: 2.0.0 => 2.0.0
    svelte: 3.54.0 => 3.54.0
    vite: 4.0.0 => 4.0.0
```

**Comment by eswat2** [comment]
just an fyi, I updated all my Solid, React & Vue projects to the latest Vite & framework plugins this morning and they all worked fine.  I have 9 Svelte projects which all failed after the update.

Hopefully there's a simple resolution for this...

**Comment by ClementNerma** [comment]
I encouter the same problem. When running `pnpm dev`:

```
> vite --host

✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@sveltejs/vite-plugin-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@sveltejs/vite-plugin-svelte" package

    node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1352:27:
      1352 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///home/clement/Projets/Hify/hify-client/node_modules/.pnpm/vite@4.0.0/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:22933:11)
    at resolvePackageEntry (file:///home/clement/Projets/Hify/hify-client/node_modules/.pnpm/vite@4.0.0/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:22928:9)
    at tryNodeResolve (file:///home/clement/Projets/Hify/hify-client/node_modules/.pnpm/vite@4.0.0/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:22668:20)
    at file:///home/clement/Projets/Hify/hify-client/node_modules/.pnpm/vite@4.0.0/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:63027:40
    at requestCallbacks.on-resolve (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1352:28)
    at handleRequest (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:720:19)
    at handleIncomingPacket (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:742:7)
    at Socket.readFromStdout (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:670:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1276:20:
      1276 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/clement/Projets/Hify/hify-client/node_modules/.pnpm/vite@4.0.0/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:63016:27)
    at handlePlugins (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1276:21)
    at buildOrServeImpl (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:965:5)
    at Object.buildOrServe (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:773:5)
    at /home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:2112:17
    at new Promise (<anonymous>)
    at Object.build (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:2111:14)
    at build (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1958:51)
    at bundleConfigFile (file:///home/clement/Projets/Hify/hify-client/node_modules/.pnpm/vite@4.0.0/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:62980:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.js:1:315:
      1 │ ...eta_url = "file:///home/clement/Projets/Hify/hify-client/vite.config.js";import { svelte } from '@sveltejs/vite-plugin-svelte'
        ╵                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /home/clement/Projets/Hify/hify-client/vite.config.js
error when starting dev server:
Error: Build failed with 1 error:
node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1352:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@sveltejs/vite-plugin-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@sveltejs/vite-plugin-svelte" package
    at failureErrorWithLog (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1591:15)
    at /home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1047:28
    at runOnEndCallbacks (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1463:61)
    at buildResponseToResult (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1045:7)
    at /home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:1157:14
    at responseCallbacks.<computed> (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:694:9)
    at handleIncomingPacket (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:749:9)
    at Socket.readFromStdout (/home/clement/Projets/Hify/hify-client/node_modules/.pnpm/esbuild@0.16.3/node_modules/esbuild/lib/main.js:670:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by dominikg** [comment]
Your package.json is missing `"type": "module"`  vite-plugin-svelte 2.0.0 is no longer available in commonjs.

Given that your vite.config.js is already written in esm syntax, i recommend you add `"type":"module"` to your package.json.

see the [FAQ](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#how-can-i-use-vite-plugin-svelte-from-commonjs) how to use it with commonjs if you have to.

Check out `npm create vite` and select svelte or svelte-ts. this creates a basic modern svelte project setup (looks like the project you linked is based on an old version of sveltejs/template). Or if you want a more complete solution, check out `pnpm create svelte`, which sets up a sveltekit project.

**Comment by ClementNerma** [comment]
I indeed had to add `"type": "module"` to my `package.json`. Then I got errors about dynamic imports, and had to change all the imports in my `vite.config.js` and `svelte.config.js` files from `const xxx = require('xxx');` to `import xxx from 'xxx';`

**Comment by eswat2** [comment]
i've updated my 9 svelte projects and made the following changes:

1. add "type": "module" to the package.json
2. renamed tailwind.config.js to tailwind.config.cjs 

those changes seem to have resolved the error and these projects are rebuilding & deploying properly after updating vite & the plugin to the latest versions.

thanks for the response !!

**Comment by eswat2** [comment]
> The changelog mentions that cjs build output is no longer available but it isn't always obvious when a project is in cjs-mode.

Yeah, i read thru the changelog and completely missed that point.  Thanks again for the help...

**Comment by trasherdk** [comment]
Improving the error message would help a lot.
Something like, when running `pnpm build` on a project, created by `pnpm create svelte@latest my-app`, you'd get:
```
> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done
```

**Comment by dominikg** [comment]
we updated the changelog to include more information. adding a better error message has to be done by vite in it's config bundling code. The only way we could show our own message was if we added back a commonjs build that always throws an error when vite-plugin-svelte is resolved via the "require" condition.
