### ISSUE TITLE
Update to 2.x @sveltejs/vite-plugin-svelte result in [ERROR] [plugin externalize-deps]

### ISSUE THREAD

**Issue by ZekyTheWolf** [sveltejs/vite-plugin-svelte#593]
### Describe the bug

After updating to 2.x version, it started giving error about Failed to resolve entry for package

More or less, cannot find solution on my own, giving there error log, config files and repo for reproduction.

[https://ptero.co/utydumyqis.coffee](vite.config.ts)
[https://ptero.co/irexovomaz.json](tsconfig.json)

### Reproduction URL

https://gitlab.com/ZekyTheWolf/laravel10

### Reproduction

1. `git clone git@gitlab.com:ZekyTheWolf/laravel10.git`
2. `composer install`
3. `cp .env.example .env`
4. `php artisan key:generate`
5. `npm install`
6. `npm run dev`

### Logs

```shell
✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@sveltejs/vite-plugin-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@sveltejs/vite-plugin-svelte" package

    node_modules/esbuild/lib/main.js:1365:27:
      1365 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///E:/laragon/www/laravel10/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22004:11)   
    at resolvePackageEntry (file:///E:/laragon/www/laravel10/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21999:9)    
    at tryNodeResolve (file:///E:/laragon/www/laravel10/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21736:20)        
    at file:///E:/laragon/www/laravel10/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62257:40
    at requestCallbacks.on-resolve (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:1365:28)
    at handleRequest (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:727:19)
    at handleIncomingPacket (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:749:7)
    at Socket.readFromStdout (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///E:/laragon/www/laravel10/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62246:27)
    at handlePlugins (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:1287:21)
    at buildOrServeImpl (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:974:5)
    at Object.buildOrServe (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:780:5)
    at E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:2131:14)
    at build (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:1978:51)
    at bundleConfigFile (file:///E:/laragon/www/laravel10/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62210:26)      

  The plugin "externalize-deps" was triggered by this import

    vite.config.ts:4:39:
      4 │ import { svelte, vitePreprocess } from '@sveltejs/vite-plugin-svelte';
        ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from E:\laragon\www\laravel10\vite.config.ts
error when starting dev server:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1365:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@sveltejs/vite-plugin-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@sveltejs/vite-plugin-svelte" package
    at failureErrorWithLog (E:\laragon\www\laravel10\node_modules\esbuild\lib\main.js:1604:15)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 7.88 GB / 15.86 GB
  Binaries:
    Node: 19.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^2.0.0 => 2.0.2
    vite: ^4.0.0 => 4.1.1
```

**Comment by bartektelec** [comment]
having the same issue

**Comment by bluwy** [comment]
Please check https://github.com/sveltejs/vite-plugin-svelte/issues?q=is%3Aissue+label%3Acommonjs+is%3Aclosed for similar issues. vite-plugin-svelte 2.0 doesn't ship CJS anymore so your setup needs to be adjusted as well.

**Comment by bluwy** [comment]
Please check https://github.com/sveltejs/vite-plugin-svelte/issues?q=is%3Aissue+label%3Acommonjs+is%3Aclosed for similar issues. vite-plugin-svelte 2.0 doesn't ship CJS anymore so your setup needs to be adjusted as well.

**Comment by ZekyTheWolf** [comment]
@bluwy Not helpfull at all... I tried what was said, add to package.json "type": "module", just resulted in problem with laravel plugin...

And after adding config that was provided in FAQ, still got same error...

So, i decided that it would be best to stick with version 1.4.x until there will be better provided support.

**Comment by meduzen** [comment]
For those who come here using the `laravel-vite-plugin`, [this is what helps](https://github.com/laravel/vite-plugin/issues/187#issuecomment-1358715065), awaiting for the Laravel team to come up with ES module instead of CommonJS.

**Comment by ZekyTheWolf** [comment]
@meduzen thanks, this helped. 

Also, its not required to add "type": "module"...

This working well enaugh :D
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

import { svelte } from '@sveltejs/vite-plugin-svelte';
const vitePreprocess = import('@sveltejs/vite-plugin-svelte').then(m => m.vitePreprocess())
import path from 'path';

export default defineConfig(({ mode }) => {
	return {
		plugins: [
            laravel({
                input: [
					'resources/scripts/main.ts'
				],
                refresh: true,
            }),
            svelte({
				preprocess: {
					//@ts-ignore
				    script:async (options) => (await vitePreprocess).script(options),
					//@ts-ignore
				    style:async (options) => (await vitePreprocess).style(options),
				}
			}),
		],

		server: {
			cors: mode === "development",
		},

		resolve: {
			alias: {
				'@Layouts':  path.resolve(__dirname, './resources/layouts/'),
				'@Components':  path.resolve(__dirname, './resources/components/'),
			}
		},

		optimizeDeps: {
			exclude: [
				'vite-plugin-svelte'
			]
		}
	}
})
```
