### ISSUE TITLE
Building skeleton project with pnpm fails with "SyntaxError: Named export 'svelteInspector' not found"

### ISSUE THREAD

**Issue by apisarev** [sveltejs/vite-plugin-svelte#971]
### Describe the bug

Building default SvelteKit project fails with pnpm.

```
error during build:
file:///C:/Users/***/import-bug-app/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@4.0.0-next.6_svelte@5.0.0-next.242_vite@5.4.2/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:2
import { svelteInspector } from '@sveltejs/vite-plugin-svelte-inspector';
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'svelteInspector' not found. The requested module '@sveltejs/vite-plugin-svelte-inspector' is a CommonJS module, which may not support all module.exports as named exports.  
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@sveltejs/vite-plugin-svelte-inspector';
const { svelteInspector } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:485:26)
    at async load_config (file:///C:/Users/***/import-bug-app/node_modules/.pnpm/@sveltejs+kit@2.5.25_@sveltejs+vite-plugin-svelte@4.0.0-next.6_svelte@5.0.0-next.242_vite@5.4_ufaaiyt2bqpun3h6qnri6hdj2e/node_modules/@sveltejs/kit/src/core/config/index.js:70:17)
    at async sveltekit (file:///C:/Users/***/import-bug-app/node_modules/.pnpm/@sveltejs+kit@2.5.25_@sveltejs+vite-plugin-svelte@4.0.0-next.6_svelte@5.0.0-next.242_vite@5.4_ufaaiyt2bqpun3h6qnri6hdj2e/node_modules/@sveltejs/kit/src/exports/vite/index.js:130:24)
    at async Promise.all (index 0)
    at async asyncFlatten (file:///C:/Users/***/import-bug-app/node_modules/.pnpm/vite@5.4.2/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:17501:12)
    at async resolveConfig (file:///C:/Users/***/import-bug-app/node_modules/.pnpm/vite@5.4.2/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:66054:27)
    at async build (file:///C:/Users/***/import-bug-app/node_modules/.pnpm/vite@5.4.2/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:65125:18)
    at async CAC.<anonymous> (file:///C:/Users/***/import-bug-app/node_modules/.pnpm/vite@5.4.2/node_modules/vite/dist/node/cli.js:828:5)
```
 

### Reproduction URL

npm create svelte@latest my-app

### Reproduction

1. `npm create svelte@latest import-bug-app`
  a. Which Svelte app template? -> Skeleton project
  b. Add type checking with TypeScript? -> Yes, using TypeScript syntax
  c. Select additional options (use arrow keys/space bar) -> Try the Svelte 5 preview (unstable!)
2. cd import-bug-app
3. pnpm install
4. pnpm run build

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 22.4.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.9.0 - ~\AppData\Roaming\npm\pnpm.CMD
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.4
    @sveltejs/kit: ^2.0.0 => 2.5.25
    @sveltejs/vite-plugin-svelte: ^4.0.0-next.6 => 4.0.0-next.6
    svelte: ^5.0.0-next.1 => 5.0.0-next.242
    vite: ^5.0.3 => 5.4.2
```

**Comment by apisarev** [comment]
Updating the Node from 22.4.1 to 22.7.0 solved the issue.

The error changed to the following warning:
```
(node:46756) [MODULE_TYPELESS_PACKAGE_JSON] Warning: file:///C:/Users/***/import-bug-app/node_modules/.pnpm/@sveltejs+vite-plugin-svelte-inspector@3.0.0-next.3_@sveltejs+vite-plugin-svelte@4.0.0-next.6_rgegepu3a6doadomdfwge5fjlq/node_modules/@sveltejs/vite-plugin-svelte-inspector/src/index.js parsed as an ES module because module syntax was detected; to avoid the performance penalty of syntax detection, add "type": "module" to C:\Users\***\import-bug-app\node_modules\.pnpm\@sveltejs+vite-plugin-svelte-inspector@3.0.0-next.3_@sveltejs+vite-plugin-svelte@4.0.0-next.6_rgegepu3a6doadomdfwge5fjlq\node_modules\package.json
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by dominikg** [comment]
this is not the first report for this issue, however type: module is set https://github.com/sveltejs/vite-plugin-svelte/blob/16eae1bc7b204c401ccfe16722a6098cc70753b0/packages/vite-plugin-svelte-inspector/package.json#L10

its possible that something in pnpm goes wrong, deleting node_modules and reinstalling might help too

**Comment by apisarev** [comment]
I've been trying a few things multiple times. I did a ppm cash reset and uninstalled ppm several times.
But, only after updating the Node version,the issue was immediately resolved in three separate projects.

**Comment by dominikg** [comment]
#922 mentioned changing the pnpm version installed by corepack helped them. i don't think its node itself but either way glad it is resolved for you. Happy svelting

**Comment by manuel3108** [comment]
Also experienced this on windows today, no pnpm cache clear / store prune whatever helped. The relevant info here was to update node, which solved the problem immediately.
