### ISSUE TITLE
Doesn't work when using Bun

### ISSUE THREAD

**Issue by knarkzel** [sveltejs/vite-plugin-svelte#994]
### Describe the bug

When running the inspector with Bun, I get `Exec format error`. This is when using `bunx --bun vite dev`. With regular `vite dev`, which uses node, the inspector works.

### Reproduction URL

https://github.com/knarkzel/sails

### Reproduction

1. Start SvelteKit project with `bunx --bun vite dev`
2. Try to use inspector

### System Info

```shell
System:
    OS: Linux 6.6 NixOS 24.11 (Vicuna) 24.11 (Vicuna)
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 9.26 GB / 15.43 GB
    Container: Yes
    Shell: 5.2.32 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 20.17.0 - ~/.nix-profile/bin/node
    Yarn: 1.22.22 - ~/.nix-profile/bin/yarn
    npm: 10.8.2 - ~/.nix-profile/bin/npm
    bun: 1.1.29 - ~/.nix-profile/bin/bun
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.7.0 
    @sveltejs/vite-plugin-svelte: ^4.0.0-next.6 => 4.0.0-next.8 
    @sveltejs/vite-plugin-svelte-inspector: ^2.1.0 => 2.1.0 
    svelte: ^5.0.0-next.1 => 5.0.0-next.264 
    vite: ^5.0.3 => 5.4.9
```

**Comment by dominikg** [comment]
cannot reproduce with a fresh project created with `pnpm create vite` (svelte-ts) and then using `bun install && bunx --bun vite dev` 

bun 1.1.30 

please try updating bun and also mention the ide/editor you are trying to use. If it is working with node, i'd not suspect the cause to be in this repo, so please report to bun.

sharing the complete cli output with the error message can also help them understand whats going on

**Comment by knarkzel** [comment]
I'm using Zed on latest master branch. This is the error:
```
8:56:02 AM [vite] Internal server error: Exec format error
      at spawn (native)
      at spawn (node:child_process:764:8)
      at spawn (node:child_process:2:15)
      at launchEditor (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:45486:36)
      at launchEditorMiddleware (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:45530:7)
      at call (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41352:7)
      at next (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41296:5)
      at viteCachedTransformMiddleware (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:61784:5)
      at call (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41352:7)
      at next (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41296:5)
      at cors (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41824:7)
      at <anonymous> (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41860:17)
      at originCallback (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41850:15)
      at <anonymous> (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41855:13)
      at optionsCallback (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41835:9)
      at corsMiddleware (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41840:7)
      at call (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41352:7)
      at next (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41296:5)
      at <anonymous> (/home/odd/sails/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:418:3)
      at call (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41352:7)
      at next (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41296:5)
      at handle (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41299:3)
      at app (/home/odd/sails/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:41164:37)
      at emit (node:events:201:48)
      at fetch (node:http:574:14)
```
Seems like the output for filename, line and column is missing in the code produced:
![image](https://github.com/user-attachments/assets/fbfc3c26-8410-421c-9e0b-4af14954c385)

**Comment by knarkzel** [comment]
Yeah that was it, I used a custom script for Zed but LAUNCH_EDITOR=zed works now.
